### ISSUE TITLE
New project addition 

### ISSUE THREAD

**Issue by payallenka** [KapilKumar7/CreativeAppIdeas#29]
I would like to add a calculator which may later work as small function that can be imported to your other/main mega project by using import. This will be made using python 100% and it will presentable in the best way possible to enhance the user experience. I wish to participate in Hacktoberfest. So if you like my proposal then kindly add the hactoberfest tag to this issue/project.

**Comment by KapilKumar7** [comment]
@payallenka Please add some new ideas only or new features Thanks. Already existing ideas will not be added.
