### ISSUE TITLE
I want to add idea about a group study app helpful for college and school students.

### ISSUE THREAD

**Issue by KratikJain10** [KapilKumar7/CreativeAppIdeas#44]
hello. 
Myself Kratik.
I want to add idea about an app.
Kindly consider this and assign me ,#hactoberfest.
Thank You.

**Comment by KapilKumar7** [comment]
Hey @KratikJain10 you can add your idea in MobileApp/Ideas.js now.

**Comment by KratikJain10** [comment]
thanks for assigning @KapilKumar7 i will add it

**Comment by KratikJain10** [comment]
@KapilKumar7 I added it ,kindly check my pull request and merge it ,if its ok.
Thank You. #hactoberfest2022.

**Comment by KapilKumar7** [comment]
@KratikJain10 You have added your idea, and then removed the whole file, you can fork the repo and contribute the idea thanks.
